import React from "react";
import { ToastContainer } from 'react-toastify'; // Container for rendering snackbar generated by child components that call notify()
import Container from "react-bootstrap/esm/Container";
import Header from "../Header";


function PageLayout(props) {
  const { children } = props;
  return (
    <>
      <Header />
      <Container className="mt-3 px-6">{children}</Container>
      <ToastContainer />
    </>
  );
}

export default PageLayout;
